apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter-service
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filter-service
  template:
    metadata:
      labels:
        app: filter-service
    spec:
      containers:
        - name: filter-service
          image: filter-service:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: bootstrap-servers
