apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-simulator
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-simulator
  template:
    metadata:
      labels:
        app: sensor-simulator
    spec:
      containers:
        - name: simulator
          image: sensor-simulator:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: bootstrap-servers
